name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.3

      - name: Setup Node environment
        uses: actions/setup-node@v2.1.4

      - name: Build
        run: npm install && npm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish . --tag ${GITHUB_REF#refs/*/}  --access public